# Generated by Django 3.2.5 on 2021-09-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_collectors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='collection_owner',
            new_name='owner',
        ),
    ]
