# Generated by Django 3.2.5 on 2021-09-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_collectors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitem',
            name='photo',
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='photo',
            field=models.ManyToManyField(to='web_collectors.Photo'),
        ),
    ]
