# Generated by Django 3.2.5 on 2021-09-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_collectors', '0002_auto_20210918_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/photo/'),
        ),
    ]
