# Generated by Django 3.2.5 on 2021-11-05 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_collectors', '0002_comment_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания коллекции'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Описание коллекции'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='web_collectors.collectiongroup', verbose_name='Группа коллекций'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название коллекции'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='Создатель коллекции'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото коллекции'),
        ),
        migrations.AlterField(
            model_name='collectiongroup',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Описание группы'),
        ),
        migrations.AlterField(
            model_name='collectiongroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='collectiongroup',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Адрес страницы с группой коллекций'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='web_collectors.collection', verbose_name='Коллекция объектов'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания объекта коллекции'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Описание объекта коллекции'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название объекта коллекции'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='photo',
            field=models.ManyToManyField(to='web_collectors.Photo', verbose_name='Фото объекта коллекции'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор коллекции'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='web_collectors.collection', verbose_name='Название коллекции'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='web_collectors.comment', verbose_name='Ответный комментарий'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=200, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='Автор коллекции'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/photo/', verbose_name='Фото'),
        ),
    ]
