# Generated by Django 3.2.5 on 2021-11-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_collectors', '0003_auto_20211105_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiongroup',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Адрес страницы с группой коллекций'),
        ),
    ]
