# Generated by Django 3.2.5 on 2021-09-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_collectors', '0003_alter_collection_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/collections'),
        ),
    ]
