# Generated by Django 3.2.5 on 2021-11-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_collectors', '0004_alter_collectiongroup_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='collection',
            order_with_respect_to=None,
        ),
    ]
