# Generated by Django 3.2.5 on 2021-09-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_collectors', '0005_alter_collection_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/photo'),
        ),
    ]
