# Generated by Django 3.2.5 on 2021-11-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_collectors', '0005_auto_20211112_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitem',
            name='photo',
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото объекта коллекции'),
        ),
    ]
