# Generated by Django 3.2.5 on 2021-09-14 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_collectors', '0006_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='web_collectors.collection'),
        ),
    ]
